# Generated by Django 4.0.1 on 2022-06-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='label',
            new_name='titles',
        ),
        migrations.RemoveField(
            model_name='building',
            name='floor',
        ),
    ]
