# Generated by Django 4.0.1 on 2022-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_rename_label_building_titles_remove_building_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='titles',
        ),
        migrations.AddField(
            model_name='building',
            name='tiles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tiles'),
        ),
    ]
