# Generated by Django 4.0.1 on 2022-06-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_remove_building_titles_building_tiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['id']},
        ),
    ]
