# Generated by Django 4.0.1 on 2022-06-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_building_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='formatID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='formatID'),
        ),
    ]
