# Generated by Django 4.0.1 on 2022-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_building_formatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='floor'),
        ),
    ]
