# Generated by Django 4.0.1 on 2022-06-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_building_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='floor',
        ),
    ]
