# Generated by Django 4.0.1 on 2022-06-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_remove_building_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='tiles',
            field=models.TextField(blank=True, null=True, verbose_name='tiles'),
        ),
    ]
