# Generated by Django 4.0.1 on 2022-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_alter_building_tiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='row',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='row'),
        ),
    ]
