# Generated by Django 4.0.1 on 2022-06-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['row']},
        ),
    ]
