# Generated by Django 4.0.1 on 2022-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tiles',
            field=models.TextField(blank=True, null=True, verbose_name='tiles'),
        ),
    ]
