# Generated by Django 4.0.1 on 2022-06-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_tiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['row']},
        ),
        migrations.AddField(
            model_name='room',
            name='row',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='row'),
        ),
    ]
